resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- pvc.yaml
- rbac.yaml
- secret.yaml
commonLabels:
  app: omni-repository-server
  owner: tommylike
commonAnnotations:
  email: tommylikehu@gmail.com
namespace: omni-repository
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/omni/omni-repository-test
  newTag: 190ebee0e1098f0c12affdd94705c8e1ef770727
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
